// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuNQ5MbKhc1qsjPIso7Sm-oyaEdMaU_J8',
    appId: '1:521701419256:web:4e16395d0ed849c496b30d',
    messagingSenderId: '521701419256',
    projectId: 'diabetes-diplo-app',
    authDomain: 'diabetes-diplo-app.firebaseapp.com',
    storageBucket: 'diabetes-diplo-app.appspot.com',
    measurementId: 'G-RJMKRGCVPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy45ySHjN1i3yt6DXMMCxTrLCk9RA8sUw',
    appId: '1:521701419256:android:a021a0d5b20634f596b30d',
    messagingSenderId: '521701419256',
    projectId: 'diabetes-diplo-app',
    storageBucket: 'diabetes-diplo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA55Zw7fqJi0pqjSgTDJBY6ow-BUzT_0Dk',
    appId: '1:521701419256:ios:d3e3493a2347a78996b30d',
    messagingSenderId: '521701419256',
    projectId: 'diabetes-diplo-app',
    storageBucket: 'diabetes-diplo-app.appspot.com',
    iosClientId: '521701419256-sr12r8dnte9t0q0v592dpictfk71vt9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.androidTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA55Zw7fqJi0pqjSgTDJBY6ow-BUzT_0Dk',
    appId: '1:521701419256:ios:d3e3493a2347a78996b30d',
    messagingSenderId: '521701419256',
    projectId: 'diabetes-diplo-app',
    storageBucket: 'diabetes-diplo-app.appspot.com',
    iosClientId: '521701419256-sr12r8dnte9t0q0v592dpictfk71vt9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.androidTesting',
  );
}
