// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEn6jPgv941HAxke1RBHonDnvroR0DymQ',
    appId: '1:771747765714:web:59ed691606430c80193c0b',
    messagingSenderId: '771747765714',
    projectId: 'diplo-app-22eeb',
    authDomain: 'diplo-app-22eeb.firebaseapp.com',
    storageBucket: 'diplo-app-22eeb.appspot.com',
    measurementId: 'G-4KP2911RL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwtpU3WIl6GCUeIR_-zL2nC73TMMu0RXk',
    appId: '1:771747765714:android:8142657ea6eead51193c0b',
    messagingSenderId: '771747765714',
    projectId: 'diplo-app-22eeb',
    storageBucket: 'diplo-app-22eeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR0gyJEfp_9XZqljAfzXmVhgTGOAq0E_Y',
    appId: '1:771747765714:ios:a83050d2e7f42f24193c0b',
    messagingSenderId: '771747765714',
    projectId: 'diplo-app-22eeb',
    storageBucket: 'diplo-app-22eeb.appspot.com',
    iosClientId: '771747765714-et5dsg6jeeqt7ger426pckj63tiv2kbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.androidTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR0gyJEfp_9XZqljAfzXmVhgTGOAq0E_Y',
    appId: '1:771747765714:ios:a83050d2e7f42f24193c0b',
    messagingSenderId: '771747765714',
    projectId: 'diplo-app-22eeb',
    storageBucket: 'diplo-app-22eeb.appspot.com',
    iosClientId: '771747765714-et5dsg6jeeqt7ger426pckj63tiv2kbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.androidTesting',
  );
}
